"use strict";
var neighbors=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];
function otsu(gray){var hist=new Uint32Array(256),sum=0,bg=0,wBg=0,best=0,threshold=127;gray.forEach(function(v){hist[v]++;});for(var i=0;i<256;i++)sum+=i*hist[i];for(i=0;i<256;i++){wBg+=hist[i];if(!wBg)continue;var wFg=gray.length-wBg;if(!wFg)break;bg+=i*hist[i];var d=bg/wBg-(sum-bg)/wFg,variance=wBg*wFg*d*d;if(variance>best){best=variance;threshold=i;}}return threshold;}
function morphology(src,w,h,dilate){var out=new Uint8Array(src.length);for(var y=1;y<h-1;y++)for(var x=1;x<w-1;x++){var value=dilate?0:1;for(var yy=-1;yy<=1;yy++)for(var xx=-1;xx<=1;xx++){var p=src[(y+yy)*w+x+xx];value=dilate?(value||p?1:0):(value&&p?1:0);}out[y*w+x]=value;}return out;}
function removeNoise(src,w,h,minPixels){var out=src.slice(),seen=new Uint8Array(src.length),queue=new Int32Array(src.length);for(var start=0;start<src.length;start++){if(!src[start]||seen[start])continue;var head=0,tail=0,component=[];queue[tail++]=start;seen[start]=1;while(head<tail){var current=queue[head++];component.push(current);var x=current%w,y=Math.floor(current/w);for(var n=0;n<neighbors.length;n++){var nx=x+neighbors[n][1],ny=y+neighbors[n][0];if(nx<0||ny<0||nx>=w||ny>=h)continue;var next=ny*w+nx;if(src[next]&&!seen[next]){seen[next]=1;queue[tail++]=next;}}}if(component.length<minPixels)for(var i=0;i<component.length;i++)out[component[i]]=0;}return out;}
function rdp(pts,eps){if(pts.length<3)return pts;var a=pts[0],b=pts[pts.length-1],dx=b.x-a.x,dy=b.y-a.y,den=dx*dx+dy*dy,best=0,index=0;for(var i=1;i<pts.length-1;i++){var p=pts[i],t=den?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/den)):0,d=Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy));if(d>best){best=d;index=i;}}if(best<=eps)return[a,b];var left=rdp(pts.slice(0,index+1),eps),right=rdp(pts.slice(index),eps);return left.slice(0,-1).concat(right);}
function traceShapes(binary,w,h){var edges=[],key=function(x,y){return y*(w+1)+x;},ink=function(x,y){return x>=0&&y>=0&&x<w&&y<h&&binary[y*w+x]===1;};for(var y=0;y<h;y++)for(var x=0;x<w;x++){if(!ink(x,y))continue;if(!ink(x,y-1))edges.push([key(x,y),key(x+1,y)]);if(!ink(x+1,y))edges.push([key(x+1,y),key(x+1,y+1)]);if(!ink(x,y+1))edges.push([key(x+1,y+1),key(x,y+1)]);if(!ink(x-1,y))edges.push([key(x,y+1),key(x,y)]);}var outgoing=new Map();edges.forEach(function(e){var list=outgoing.get(e[0])||[];list.push(e[1]);outgoing.set(e[0],list);});var loops=[];while(outgoing.size){var start=outgoing.keys().next().value,current=start,loop=[start];for(var guard=0;guard<edges.length+1;guard++){var list=outgoing.get(current);if(!list||!list.length)break;var next=list.pop();if(!list.length)outgoing.delete(current);current=next;if(current===start)break;loop.push(current);}if(loop.length>=4)loops.push(loop);if(loops.length>12000)throw new Error("图片背景过于复杂，请先裁剪到笔记区域后重试");}return loops;}
async function vectorize(file,smoothness){var bitmap=await createImageBitmap(file),maxEdge=2400,ratio=Math.min(1,maxEdge/Math.max(bitmap.width,bitmap.height)),w=Math.max(1,Math.round(bitmap.width*ratio)),h=Math.max(1,Math.round(bitmap.height*ratio)),canvas=new OffscreenCanvas(w,h),ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.drawImage(bitmap,0,0,w,h);bitmap.close();var rgba=ctx.getImageData(0,0,w,h).data,gray=new Uint8Array(w*h);for(var i=0;i<gray.length;i++)gray[i]=Math.round(.299*rgba[i*4]+.587*rgba[i*4+1]+.114*rgba[i*4+2]);var integral=new Float64Array((w+1)*(h+1));for(var y=1;y<=h;y++){var row=0;for(var x=1;x<=w;x++){row+=gray[(y-1)*w+x-1];integral[y*(w+1)+x]=integral[(y-1)*(w+1)+x]+row;}}var normalized=new Uint8Array(gray.length),radius=12;for(y=0;y<h;y++)for(x=0;x<w;x++){var x0=Math.max(0,x-radius),y0=Math.max(0,y-radius),x1=Math.min(w-1,x+radius),y1=Math.min(h-1,y+radius),area=(x1-x0+1)*(y1-y0+1),mean=(integral[(y1+1)*(w+1)+x1+1]-integral[y0*(w+1)+x1+1]-integral[(y1+1)*(w+1)+x0]+integral[y0*(w+1)+x0])/area;normalized[y*w+x]=Math.max(0,Math.min(255,Math.round(gray[y*w+x]*255/(mean||255))));}var threshold=otsu(normalized),binary=new Uint8Array(w*h);for(i=0;i<binary.length;i++)binary[i]=normalized[i]<threshold?1:0;var closed=removeNoise(morphology(morphology(binary,w,h,true),w,h,false),w,h,2),raw=traceShapes(closed,w,h),epsilon=.08+(smoothness/100)*.45,scale=Math.min(1200/w,800/h),offsetX=(1200-w*scale)/2,offsetY=(800-h*scale)/2,contours=raw.map(function(loop){var step=Math.max(1,Math.ceil(loop.length/6000)),sampled=step===1?loop:loop.filter(function(_,index){return index%step===0;});return rdp(sampled.map(function(n){return{x:(n%(w+1))*scale+offsetX,y:Math.floor(n/(w+1))*scale+offsetY};}),Math.max(.3,epsilon*.55)*scale);}).filter(function(c){return c.length>=3;});return contours.length?[{contours:contours}]:[];}
self.onmessage=async function(event){try{var shapes=await vectorize(event.data.file,event.data.smoothness);self.postMessage({shapes:shapes});}catch(error){self.postMessage({error:error&&error.message?error.message:"矢量转换失败"});}};
