permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8


title: Be A Better Me
author: Bin Li
email: bin.li.daily@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A reader, learner and thinker.

# social links
twitter_username: gitlinux
github_username:  binlidaily
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-seo-tag
  - github-pages
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page/:num/"



# Add disqus username for Disqus comment board:
disqus:
  shortname: gitlinux
# Analytics and webmaster tools stuff goes here
google_analytics: "UA-111874196-1"