# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Be A Better Me
paginate:       5
baseurl:        ""
url:            "https://binlidaily.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Bin Li
  url:          http://binlidaily.github.io
  email:        bin.li.daily@gmail.com

# Custom vars
version:        3.4.1
github:
  # repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
