url: "https://www.hi-bin.com"
baseurl: ""
title: "Know Thyself"
description: "阅读、技术与生活札记"
timezone: "Asia/Shanghai"

navbar-links:
  Blogs: ""
  About Me: "aboutme"

avatar: "/img/avatar-icon.png"
author:
  name: gitlinux

social-network-links:
  rss: true
  email: "gitlinux@gmail.com"
  github: gitlinux

disqus: gitlinux
excerpt_length: 50
title-separator: "·"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 6
link-tags: true

kramdown:
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ""
    values:
      layout: page

plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - vendor
